/**
 * Dicionário EN → PT-BR para significados do KANJIDIC2.
 * Cobre os primeiros significados dos kanjis JLPT N5–N1.
 */
const MEANING_MAP = {
  // ── Números ────────────────────────────────────────────────────────────────
  'one': 'um', 'two': 'dois', 'three': 'três', 'four': 'quatro',
  'five': 'cinco', 'six': 'seis', 'seven': 'sete', 'eight': 'oito',
  'nine': 'nove', 'ten': 'dez', 'hundred': 'cem', 'thousand': 'mil',
  'ten thousand': 'dez mil', 'ten-thousand': 'dez mil', 'zero': 'zero',
  'hundred million': 'cem milhões', 'myriad': 'miriade',

  // ── Tempo ──────────────────────────────────────────────────────────────────
  'day': 'dia', 'sun': 'sol', 'japan': 'Japão',
  'month': 'mês', 'moon': 'lua',
  'year': 'ano', 'time': 'tempo', 'hour': 'hora', 'minute': 'minuto',
  'morning': 'manhã', 'evening': 'tarde/noite', 'night': 'noite',
  'noon': 'meio-dia', 'midnight': 'meia-noite', 'daytime': 'dia/período diurno',
  'nightfall': 'entardecer', 'dawn': 'amanhecer', 'daybreak': 'alvorada',
  'week': 'semana', 'now': 'agora', 'before': 'antes', 'after': 'depois',
  'previous': 'anterior', 'next': 'próximo', 'ahead': 'à frente',
  'early': 'cedo', 'late': 'tarde', 'later': 'depois/mais tarde',
  'spring': 'primavera', 'summer': 'verão', 'autumn': 'outono', 'fall': 'outono',
  'winter': 'inverno', 'season': 'estação do ano',
  'old': 'antigo/velho', 'ancient': 'antigo', 'new': 'novo', 'modern': 'moderno',
  'beginning': 'início', 'end': 'fim', 'origin': 'origem',
  'long time': 'longo tempo', 'permanent': 'permanente', 'eternity': 'eternidade',
  'era': 'era', 'epoch': 'época', 'generation': 'geração',
  'once upon a time': 'era uma vez', 'old times': 'tempos antigos',

  // ── Natureza ───────────────────────────────────────────────────────────────
  'mountain': 'montanha', 'river': 'rio', 'stream': 'riacho', 'brook': 'córrego',
  'water': 'água', 'fire': 'fogo', 'flame': 'chama', 'blaze': 'labareda',
  'tree': 'árvore', 'wood': 'madeira', 'forest': 'floresta', 'grove': 'bosque',
  'woods': 'floresta/bosque', 'lumber': 'madeira serrada',
  'earth': 'terra', 'soil': 'solo', 'ground': 'chão', 'land': 'terra/terreno',
  'sky': 'céu', 'cloud': 'nuvem', 'rain': 'chuva', 'snow': 'neve',
  'wind': 'vento', 'thunder': 'trovão', 'lightning': 'relâmpago',
  'storm': 'tempestade', 'fog': 'névoa/neblina', 'mist': 'névoa',
  'frost': 'geada', 'dew': 'orvalho', 'ice': 'gelo', 'icicle': 'estalactite de gelo',
  'stone': 'pedra', 'rock': 'rocha', 'sand': 'areia', 'cliff': 'falésia',
  'island': 'ilha', 'sea': 'mar', 'ocean': 'oceano', 'lake': 'lago',
  'pond': 'lagoa', 'field': 'campo', 'plain': 'planície', 'plains': 'planícies',
  'meadow': 'prado', 'swamp': 'pântano', 'marsh': 'pântano/charco',
  'valley': 'vale', 'gulf': 'golfo', 'bay': 'baía', 'beach': 'praia',
  'seacoast': 'litoral', 'seashore': 'costa marítima',
  'rice field': 'arrozal', 'rice paddy': 'arrozal',
  'grass': 'grama/erva', 'flower': 'flor', 'blossom': 'florescer/floração',
  'leaf': 'folha', 'root': 'raiz', 'branch': 'galho', 'seed': 'semente',
  'fruit': 'fruta', 'bud': 'broto', 'twig': 'galho fino',
  'pine tree': 'pinheiro', 'cedar': 'cedro', 'bamboo': 'bambu',
  'plum': 'ameixa', 'cherry': 'cereja', 'peach': 'pêssego',
  'apricot': 'damasco', 'chestnut': 'castanha', 'maple': 'bordo',
  'willow': 'salgueiro', 'wisteria': 'glicineia',
  'gold': 'ouro', 'silver': 'prata', 'iron': 'ferro', 'metal': 'metal',
  'copper': 'cobre', 'tin': 'estanho',
  'animal': 'animal', 'bird': 'pássaro', 'fish': 'peixe', 'insect': 'inseto',
  'dog': 'cachorro', 'cat': 'gato', 'horse': 'cavalo', 'cow': 'vaca',
  'ox': 'boi', 'pig': 'porco', 'sheep': 'ovelha', 'monkey': 'macaco',
  'dragon': 'dragão', 'snake': 'cobra', 'tiger': 'tigre', 'rabbit': 'coelho',
  'deer': 'cervo', 'bear': 'urso', 'boar': 'javali', 'whale': 'baleia',
  'hawk': 'falcão', 'falcon': 'falcão', 'crane': 'garça/guindaste',
  'large bird': 'ave grande', 'carp': 'carpa',
  'silk': 'seda', 'silkworm': 'bicho-da-seda',

  // ── Direções e posições ────────────────────────────────────────────────────
  'east': 'leste', 'west': 'oeste', 'south': 'sul', 'north': 'norte',
  'right': 'direita', 'left': 'esquerda',
  'above': 'acima', 'up': 'cima', 'superior': 'superior',
  'below': 'abaixo', 'down': 'baixo', 'inferior': 'inferior',
  'middle': 'meio', 'center': 'centro', 'inside': 'dentro', 'in': 'dentro',
  'outside': 'fora', 'between': 'entre', 'beside': 'ao lado',
  'front': 'frente', 'in front': 'na frente', 'behind': 'atrás',
  'back': 'atrás', 'side': 'lado', 'horizontal': 'horizontal',
  'vertical': 'vertical', 'diagonal': 'diagonal',

  // ── Pessoas e família ──────────────────────────────────────────────────────
  'person': 'pessoa', 'people': 'pessoas', 'human': 'humano/a',
  'man': 'homem', 'male': 'masculino', 'woman': 'mulher', 'female': 'feminino',
  'child': 'criança', 'boy': 'menino', 'girl': 'menina',
  'baby': 'bebê', 'adult': 'adulto', 'elder': 'idoso', 'youth': 'jovem',
  'young': 'jovem', 'old man': 'velho', 'old woman': 'senhora idosa',
  'father': 'pai', 'mother': 'mãe', 'parent': 'pai/mãe',
  'son': 'filho', 'daughter': 'filha',
  'older brother': 'irmão mais velho', 'elder brother': 'irmão mais velho',
  'younger brother': 'irmão mais novo', 'big brother': 'irmão mais velho',
  'older sister': 'irmã mais velha', 'elder sister': 'irmã mais velha',
  'younger sister': 'irmã mais nova',
  'husband': 'marido', 'wife': 'esposa', 'couple': 'casal',
  'family': 'família', 'relative': 'parente', 'ancestor': 'ancestral',
  'grandchild': 'neto/a', 'heir': 'herdeiro', 'orphan': 'órfão',
  'widow': 'viúva', 'uncle': 'tio',
  'friend': 'amigo/a', 'companion': 'companheiro/a', 'partner': 'parceiro/a',
  'comrade': 'camarada', 'colleague': 'colega',
  'teacher': 'professor/a', 'student': 'estudante', 'pupil': 'aluno/a',
  'master': 'mestre', 'lord': 'senhor', 'king': 'rei', 'queen': 'rainha',
  'emperor': 'imperador', 'empress': 'imperatriz', 'princess': 'princesa',
  'sovereign': 'soberano',
  'samurai': 'samurai', 'warrior': 'guerreiro', 'soldier': 'soldado',
  'doctor': 'médico/a', 'nurse': 'enfermeiro/a',
  'merchant': 'comerciante', 'farmer': 'fazendeiro', 'craftsman': 'artesão',
  'artisan': 'artesão', 'actor': 'ator', 'performer': 'artista',
  'general': 'general', 'officer': 'oficial', 'military officer': 'oficial militar',
  'bureaucrat': 'burocrata', 'retainer': 'vassalo',
  'burglar': 'ladrão', 'villain': 'vilão', 'slave': 'escravo',
  'gentleman': 'cavalheiro', 'commoner': 'plebeu', 'lad': 'rapaz',
  'spy': 'espião', 'messenger': 'mensageiro',
  'mediator': 'mediador', 'assistant': 'assistente',

  // ── Corpo humano ───────────────────────────────────────────────────────────
  'mouth': 'boca', 'eye': 'olho', 'ear': 'orelha', 'nose': 'nariz',
  'hand': 'mão', 'leg': 'perna', 'foot': 'pé', 'arm': 'braço',
  'finger': 'dedo', 'toe': 'dedo do pé', 'head': 'cabeça', 'face': 'rosto',
  'hair': 'cabelo', 'tooth': 'dente', 'lip': 'lábio', 'tongue': 'língua',
  'neck': 'pescoço', 'shoulder': 'ombro', 'chest': 'peito', 'stomach': 'estômago',
  'abdomen': 'abdômen', 'back (body)': 'costas', 'hip': 'quadril',
  'knee': 'joelho', 'elbow': 'cotovelo', 'forehead': 'testa',
  'eyebrow': 'sobrancelha', 'eyeball': 'globo ocular', 'jaw': 'queixo',
  'loins': 'lombos', 'womb': 'útero', 'bosom': 'seio',
  'heart': 'coração', 'blood': 'sangue', 'bone': 'osso', 'skin': 'pele',
  'muscle': 'músculo', 'liver': 'fígado', 'lung': 'pulmão', 'lungs': 'pulmões',
  'gall bladder': 'vesícula biliar', 'intestines': 'intestinos',
  'marrow': 'medula', 'membrane': 'membrana',
  'body': 'corpo', 'spirit': 'espírito', 'soul': 'alma',
  'breath': 'respiração/fôlego', 'sweat': 'suor', 'tears': 'lágrimas',

  // ── Cores ──────────────────────────────────────────────────────────────────
  'white': 'branco/a', 'black': 'preto/a', 'red': 'vermelho/a',
  'blue': 'azul', 'green': 'verde', 'yellow': 'amarelo/a',
  'orange': 'laranja', 'purple': 'roxo/a', 'pink': 'rosa',
  'brown': 'marrom', 'gray': 'cinza', 'grey': 'cinza',
  'crimson': 'carmesim', 'scarlet': 'escarlate', 'dark blue': 'azul escuro',
  'indigo': 'índigo', 'vermilion': 'vermelhão',
  'color': 'cor', 'colour': 'cor', 'light': 'luz/claro', 'dark': 'escuro',
  'bright': 'brilhante/claro', 'brilliant': 'brilhante', 'radiance': 'radiância',
  'shine': 'brilhar', 'glassy': 'vítreo', 'glossy': 'brilhoso',
  'transparent': 'transparente', 'pure': 'puro/a',

  // ── Tamanho e quantidade ───────────────────────────────────────────────────
  'big': 'grande', 'large': 'grande', 'huge': 'enorme', 'giant': 'gigante',
  'gigantic': 'gigantesco',
  'small': 'pequeno/a', 'little': 'pequeno/a', 'tiny': 'minúsculo/a',
  'high': 'alto/a', 'tall': 'alto/a', 'low': 'baixo/a', 'short': 'curto/a',
  'long': 'longo/a', 'wide': 'largo/a', 'broad': 'amplo/a',
  'narrow': 'estreito/a', 'thick': 'grosso/a', 'thin': 'fino/a',
  'deep': 'fundo/profundo', 'shallow': 'raso/a',
  'heavy': 'pesado/a', 'light (weight)': 'leve', 'weight': 'peso',
  'many': 'muitos/as', 'much': 'muito', 'few': 'poucos/as',
  'abundant': 'abundante', 'bountiful': 'abundante/farto', 'fertile': 'fértil',
  'rich': 'rico/a', 'luxury': 'luxo', 'luxuriant': 'exuberante',
  'poor': 'pobre', 'poverty': 'pobreza', 'scarce': 'escasso',
  'all': 'tudo/todo', 'half': 'metade', 'full': 'cheio/a', 'empty': 'vazio/a',
  'excessive': 'excessivo', 'surplus': 'excedente', 'superfluous': 'supérfluo',
  'double': 'dobro', 'duplicate': 'duplicado',
  'first': 'primeiro/a', 'last': 'último/a', 'only': 'apenas/só',
  'both': 'ambos', 'each': 'cada', 'various': 'vários', 'several': 'vários',
  'entire': 'inteiro', 'whole': 'todo/inteiro',

  // ── Ações ──────────────────────────────────────────────────────────────────
  'see': 'ver', 'look': 'olhar', 'watch': 'observar', 'look at': 'olhar para',
  'look back': 'olhar para trás', 'stare': 'encarar',
  'hear': 'ouvir', 'listen': 'escutar', 'speak': 'falar', 'talk': 'conversar',
  'say': 'dizer', 'shout': 'gritar', 'whisper': 'sussurrar',
  'read': 'ler', 'write': 'escrever', 'draw': 'desenhar',
  'study': 'estudar', 'learning': 'aprendizado', 'teach': 'ensinar',
  'learn': 'aprender', 'practice': 'praticar', 'memorize': 'memorizar',
  'know': 'saber/conhecer', 'understand': 'entender', 'think': 'pensar',
  'remember': 'lembrar', 'forget': 'esquecer', 'believe': 'acreditar',
  'imagine': 'imaginar', 'consider': 'considerar', 'decide': 'decidir',
  'choose': 'escolher', 'plan': 'planejar',
  'eat': 'comer', 'food': 'comida', 'drink': 'beber', 'cook': 'cozinhar',
  'boil': 'ferver', 'bake': 'assar', 'fry': 'fritar',
  'go': 'ir', 'come': 'vir', 'return': 'retornar/voltar', 'arrive': 'chegar',
  'leave': 'partir', 'exit': 'sair', 'enter': 'entrar',
  'walk': 'caminhar', 'run': 'correr', 'jump': 'pular', 'fly': 'voar',
  'swim': 'nadar', 'climb': 'escalar', 'fall': 'cair', 'rise': 'subir',
  'ascend': 'ascender', 'descend': 'descer', 'soar': 'planar/voar alto',
  'stand up': 'ficar em pé', 'sit': 'sentar', 'sleep': 'dormir', 'wake': 'acordar',
  'rest': 'descanso', 'lie down': 'deitar',
  'live': 'viver/morar', 'life': 'vida', 'death': 'morte', 'die': 'morrer',
  'born': 'nascer', 'birth': 'nascimento', 'grow': 'crescer',
  'buy': 'comprar', 'sell': 'vender', 'pay': 'pagar',
  'trade': 'comércio', 'exchange': 'trocar', 'lend': 'emprestar',
  'borrow': 'tomar emprestado',
  'work': 'trabalhar', 'rest (break)': 'descansar', 'play': 'brincar/jogar',
  'hurry': 'apressar-se',
  'open': 'abrir', 'close': 'fechar', 'break': 'quebrar', 'cut': 'cortar',
  'pull': 'puxar', 'push': 'empurrar', 'lift': 'levantar', 'carry': 'carregar',
  'throw': 'lançar', 'catch': 'pegar/capturar', 'hit': 'bater/acertar',
  'pierce': 'perfurar', 'stab': 'esfaquear', 'shoot': 'atirar',
  'put': 'colocar', 'take': 'pegar/levar', 'give': 'dar', 'receive': 'receber',
  'send': 'enviar', 'hold': 'segurar', 'hang': 'pendurar', 'wrap': 'embrulhar',
  'use': 'usar', 'make': 'fazer', 'build': 'construir', 'create': 'criar',
  'produce': 'produzir', 'manufacture': 'fabricar', 'forge': 'forjar',
  'burn': 'queimar', 'extinguish': 'apagar/extinguir', 'heat': 'aquecer',
  'melt': 'derreter', 'freeze': 'congelar', 'dry': 'secar', 'wet': 'molhar',
  'wash': 'lavar', 'clean': 'limpar', 'sweep': 'varrer', 'rub': 'esfregar',
  'meet': 'encontrar', 'wait': 'esperar', 'ask': 'perguntar', 'answer': 'responder',
  'help': 'ajudar', 'protect': 'proteger', 'fight': 'lutar', 'win': 'vencer',
  'lose': 'perder', 'attack': 'atacar', 'defend': 'defender',
  'kill': 'matar', 'rob': 'roubar', 'steal': 'roubar', 'capture': 'capturar',
  'arrest': 'prender', 'escape': 'escapar', 'hide': 'esconder',
  'begin': 'começar', 'start': 'iniciar', 'stop': 'parar', 'finish': 'terminar',
  'continue': 'continuar', 'change': 'mudar', 'move': 'mover',
  'increase': 'aumentar', 'decrease': 'diminuir', 'add': 'adicionar',
  'calculate': 'calcular', 'count': 'contar', 'measure': 'medir',
  'carry out': 'realizar', 'proceed': 'prosseguir', 'advance': 'avançar',
  'become': 'tornar-se', 'acquire': 'adquirir', 'gain': 'ganhar',
  'lose (something)': 'perder', 'lack': 'faltar', 'need': 'precisar',
  'spread': 'espalhar', 'scatter': 'dispersar', 'distribute': 'distribuir',
  'gather': 'reunir', 'collect': 'coletar', 'store': 'armazenar',
  'accumulate': 'acumular', 'consume': 'consumir', 'exhaust': 'esgotar',
  'overflow': 'transbordar', 'pour': 'derramar', 'fill': 'encher',
  'divide': 'dividir', 'separate': 'separar', 'join': 'unir',
  'connect': 'conectar', 'attach': 'anexar', 'tie': 'amarrar',
  'bind': 'ligar/atar', 'twist': 'torcer', 'bend': 'dobrar/curvar',
  'stretch': 'esticar', 'shrink': 'encolher', 'expand': 'expandir',
  'dig': 'cavar', 'drill': 'perfurar', 'carve': 'esculpir',
  'polish': 'polir', 'grind': 'moer', 'cut down': 'cortar',
  'plant': 'plantar', 'cultivate': 'cultivar', 'harvest': 'colher',
  'raise': 'criar/levantar', 'breed': 'criar', 'domesticate': 'domesticar',
  'travel': 'viajar', 'journey': 'jornada', 'going': 'ida',
  'ride': 'cavalgar/andar de', 'sail': 'navegar', 'navigate': 'navegar',
  'submit': 'submeter', 'obey': 'obedecer', 'follow': 'seguir',
  'lead': 'liderar', 'manage': 'gerenciar', 'control': 'controlar',
  'organize': 'organizar', 'arrange': 'organizar',
  'publish': 'publicar', 'print': 'imprimir', 'record': 'registrar',
  'investigate': 'investigar', 'research': 'pesquisa', 'examine': 'examinar',
  'praise': 'elogiar', 'criticize': 'criticar', 'blame': 'culpar',
  'punish': 'punir', 'reward': 'recompensar',
  'celebrate': 'celebrar', 'enjoy': 'aproveitar', 'laugh': 'rir',
  'cry': 'chorar', 'grieve': 'lamentar', 'fear': 'temer',
  'hate': 'odiar', 'love': 'amar', 'miss': 'sentir falta',
  'desire': 'desejar', 'wish': 'desejar', 'hope': 'esperar',
  'pray': 'rezar', 'worship': 'adorar',
  'discuss': 'discutir', 'consult': 'consultar',
  'agree': 'concordar', 'decide': 'decidir', 'permit': 'permitir',
  'refuse': 'recusar', 'reject': 'rejeitar', 'prohibit': 'proibir',
  'accept': 'aceitar', 'approve': 'aprovar',
  'show': 'mostrar', 'display': 'exibir', 'reveal': 'revelar',
  'hide (secret)': 'esconder', 'conceal': 'ocultar',
  'warn': 'advertir', 'report': 'reportar', 'announce': 'anunciar',
  'invite': 'convidar', 'introduce': 'apresentar', 'entrust': 'confiar/entregar',
  'deliver': 'entregar', 'send back': 'devolver',
  'beg': 'suplicar', 'petition': 'peticionar', 'request': 'solicitar',
  'compensate': 'compensar', 'repay': 'reembolsar', 'pledge': 'prometer',
  'promise': 'prometer', 'vow': 'jurar',
  'absorb': 'absorver', 'suck': 'sugar',
  'sew': 'costurar', 'weave': 'tecer', 'spin': 'fiar', 'dye': 'tingir',
  'paint': 'pintar', 'draw (picture)': 'desenhar', 'sketch': 'esboçar',
  'engrave': 'gravar', 'seal': 'selar',
  'lure': 'atrair', 'attract': 'atrair', 'seduce': 'seduzir',
  'approach': 'aproximar-se', 'draw near': 'aproximar-se',
  'pass': 'passar', 'cross': 'cruzar', 'reach': 'alcançar',
  'reach out': 'estender a mão',
  'sink': 'afundar', 'drown': 'afogar', 'float': 'flutuar', 'drift': 'derivar',
  'overflow': 'transbordar', 'drip': 'pingar', 'droop': 'murchar',
  'flow': 'fluir', 'leak': 'vazar', 'pour (liquid)': 'verter',
  'boil (water)': 'ferver',
  'rub': 'esfregar', 'wipe': 'limpar/apagar',
  'compete': 'competir', 'contend': 'disputar',
  'overcome': 'superar', 'conquer': 'conquistar', 'defeat': 'derrotar',
  'subjugate': 'subjugar', 'overthrow': 'derrubar',
  'resist': 'resistir', 'withstand': 'suportar', 'endure': 'aguentar',
  'support': 'apoiar', 'rely': 'depender', 'trust': 'confiar',
  'abandon': 'abandonar', 'quit': 'desistir', 'retire': 'aposentar-se',
  'resign': 'renunciar', 'withdraw': 'retirar-se', 'retreat': 'recuar',
  'escape': 'escapar', 'flee': 'fugir',
  'climb': 'escalar', 'mount': 'escalar/montar',
  'penetrate': 'penetrar', 'bore through': 'atravessar',

  // ── Lugares e construções ──────────────────────────────────────────────────
  'country': 'país', 'nation': 'nação', 'province': 'província',
  'prefecture': 'prefeitura', 'district': 'distrito', 'region': 'região',
  'county': 'condado', 'borough': 'bairro/município',
  'city': 'cidade', 'town': 'cidade/vila', 'village': 'vila',
  'capital': 'capital', 'metropolis': 'metrópole',
  'school': 'escola', 'university': 'universidade', 'library': 'biblioteca',
  'hospital': 'hospital', 'store': 'loja', 'shop': 'loja', 'market': 'mercado',
  'station': 'estação', 'airport': 'aeroporto', 'harbor': 'porto',
  'road': 'estrada', 'street': 'rua', 'bridge': 'ponte', 'tunnel': 'túnel',
  'avenue': 'avenida', 'boulevard': 'bulevard', 'path': 'caminho/trilha',
  'road-way': 'caminho/estrada', 'route': 'rota',
  'door': 'porta', 'gate': 'portão', 'window': 'janela', 'wall': 'parede/muro',
  'room': 'quarto/sala', 'house': 'casa', 'home': 'lar',
  'building': 'edifício', 'hall': 'salão', 'mansion': 'mansão',
  'castle': 'castelo', 'palace': 'palácio', 'tower': 'torre',
  'temple': 'templo', 'shrine': 'santuário', 'church': 'igreja',
  'pagoda': 'pagode', 'inn': 'pousada', 'dormitory': 'dormitório',
  'park': 'parque', 'garden': 'jardim', 'farm': 'fazenda',
  'factory': 'fábrica', 'office': 'escritório', 'bank': 'banco',
  'bureau': 'repartição', 'government office': 'repartição pública',
  'prison': 'prisão', 'barracks': 'quartel',
  'warehouse': 'armazém', 'storehouse': 'depósito', 'godown': 'armazém',
  'den': 'covil', 'cave': 'caverna', 'cellar': 'porão',
  'podium': 'pódio', 'stage': 'palco/etapa', 'pavilion': 'pavilhão',

  // ── Objetos cotidianos ─────────────────────────────────────────────────────
  'book': 'livro', 'letter': 'carta', 'paper': 'papel', 'pen': 'caneta',
  'pencil': 'lápis', 'notebook': 'caderno', 'document': 'documento',
  'map': 'mapa', 'picture': 'imagem/quadro', 'photo': 'foto',
  'scroll': 'pergaminho', 'inscription': 'inscrição',
  'bag': 'bolsa/mochila', 'box': 'caixa', 'bottle': 'garrafa',
  'cup': 'xícara/copo', 'plate': 'prato', 'dish': 'prato', 'bowl': 'tigela',
  'tray': 'bandeja', 'pot': 'panela', 'vat': 'tonel',
  'knife': 'faca', 'sword': 'espada', 'blade': 'lâmina',
  'bow': 'arco', 'arrow': 'flecha', 'shield': 'escudo', 'armor': 'armadura',
  'axe': 'machado', 'halberd': 'alabarda', 'sickle': 'foice',
  'needle': 'agulha', 'thread': 'linha', 'rope': 'corda', 'cord': 'cordão',
  'wire': 'arame', 'chain': 'corrente',
  'plank': 'prancha/tábua', 'board': 'tábua/placa', 'frame': 'moldura/estrutura',
  'pillar': 'pilar/coluna', 'shelf': 'prateleira', 'desk': 'mesa',
  'rod': 'haste/vara', 'stick': 'graveto', 'log': 'tronco',
  'money': 'dinheiro', 'coin': 'moeda', 'price': 'preço', 'tax': 'imposto',
  'salary': 'salário', 'fee': 'taxa/tarifa', 'fare': 'tarifa',
  'income': 'renda', 'earnings': 'ganhos', 'profit': 'lucro',
  'car': 'carro', 'train': 'trem', 'bus': 'ônibus', 'boat': 'barco',
  'ship': 'navio', 'airplane': 'avião', 'bicycle': 'bicicleta',
  'clothes': 'roupas', 'clothing': 'vestimenta', 'garment': 'vestimenta',
  'hat': 'chapéu', 'cap': 'boné', 'shoes': 'sapatos', 'sandals': 'sandálias',
  'sash': 'faixa', 'kimono': 'quimono',
  'rice': 'arroz', 'bread': 'pão', 'meat': 'carne', 'egg': 'ovo',
  'fish (food)': 'peixe', 'beans': 'feijão', 'vegetable': 'vegetal',
  'sugar': 'açúcar', 'salt': 'sal', 'oil': 'óleo', 'vinegar': 'vinagre',
  'sake': 'sakê',
  'ball': 'bola', 'drum': 'tambor', 'bell': 'sino', 'harp': 'harpa',
  'flute': 'flauta', 'pipe': 'flauta/tubo',
  'mirror': 'espelho', 'lamp': 'lâmpada', 'candle': 'vela',
  'medicine': 'remédio', 'drug': 'droga/remédio',
  'poison': 'veneno', 'ink': 'tinta', 'black ink': 'tinta preta',
  'seal (stamp)': 'selo/carimbo', 'tag': 'etiqueta', 'badge': 'distintivo',
  'ticket': 'ingresso/bilhete', 'ballot': 'cédula/votação',
  'gun': 'arma de fogo', 'bullet': 'bala', 'bomb': 'bomba',
  'cannon': 'canhão', 'ammunition': 'munição',
  'umbrella': 'guarda-chuva', 'fan (hand)': 'leque',
  'mask': 'máscara', 'puppet': 'fantoche',
  'furniture': 'mobília', 'utensil': 'utensílio', 'tool': 'ferramenta',
  'instrument': 'instrumento', 'machine': 'máquina',
  'skeleton': 'esqueleto', 'skull': 'crânio', 'remains': 'restos/ruínas',

  // ── Conceitos abstratos ────────────────────────────────────────────────────
  'language': 'idioma/língua', 'character': 'caractere', 'writing': 'escrita',
  'text': 'texto', 'meaning': 'significado', 'word': 'palavra', 'words': 'palavras',
  'sentence': 'frase', 'phrase': 'frase', 'paragraph': 'parágrafo',
  'name': 'nome', 'title': 'título', 'nickname': 'apelido',
  'family name': 'sobrenome', 'surname': 'sobrenome',
  'number': 'número', 'letter (alphabet)': 'letra', 'symbol': 'símbolo',
  'sound': 'som', 'voice': 'voz', 'noise': 'barulho', 'melody': 'melodia',
  'song': 'canção', 'music': 'música', 'rhythm': 'ritmo', 'rhyme': 'rima',
  'poem': 'poema', 'tale': 'conto', 'story': 'história', 'novel': 'romance',
  'drama': 'drama', 'art': 'arte', 'culture': 'cultura',
  'power': 'poder', 'strength': 'força', 'energy': 'energia',
  'ability': 'habilidade', 'skill': 'habilidade', 'talent': 'talento',
  'genius': 'gênio', 'wisdom': 'sabedoria', 'intelligence': 'inteligência',
  'logic': 'lógica', 'science': 'ciência', 'philosophy': 'filosofia',
  'love': 'amor', 'peace': 'paz', 'war': 'guerra', 'battle': 'batalha',
  'conflict': 'conflito', 'victory': 'vitória', 'defeat (loss)': 'derrota',
  'justice': 'justiça', 'law': 'lei', 'rule': 'regra', 'constitution': 'constituição',
  'freedom': 'liberdade', 'rights': 'direitos', 'permission': 'permissão',
  'prohibition': 'proibição', 'obligation': 'obrigação',
  'truth': 'verdade', 'lie': 'mentira', 'mistake': 'erro', 'error': 'erro',
  'sin': 'pecado', 'crime': 'crime', 'guilt': 'culpa',
  'punishment': 'punição', 'penalty': 'penalidade',
  'happiness': 'felicidade', 'sadness': 'tristeza', 'joy': 'alegria',
  'sorrow': 'pesar', 'grief': 'luto', 'suffering': 'sofrimento',
  'pleasure': 'prazer', 'anger': 'raiva', 'fear': 'medo',
  'anxiety': 'ansiedade', 'worry': 'preocupação',
  'hope': 'esperança', 'dream': 'sonho', 'ambition': 'ambição',
  'desire': 'desejo', 'longing': 'saudade', 'affinity': 'afinidade',
  'kindness': 'bondade', 'mercy': 'misericórdia', 'grace': 'graça',
  'loyalty': 'lealdade', 'faith': 'fé', 'trust (faith)': 'confiança',
  'sincerity': 'sinceridade', 'honesty': 'honestidade',
  'honor': 'honra', 'shame': 'vergonha', 'pride': 'orgulho',
  'dignity': 'dignidade', 'respect': 'respeito', 'humility': 'humildade',
  'virtue': 'virtude', 'morality': 'moralidade', 'moral': 'moral',
  'ethics': 'ética', 'benevolence': 'benevolência', 'filial piety': 'piedade filial',
  'duty': 'dever', 'responsibility': 'responsabilidade',
  'tradition': 'tradição', 'custom': 'costume', 'ceremony': 'cerimônia',
  'ritual': 'ritual', 'religion': 'religião', 'buddhism': 'budismo',
  'prayer': 'oração', 'blessing': 'bênção', 'salvation': 'salvação',
  'fate': 'destino', 'luck': 'sorte', 'fortune': 'fortuna',
  'danger': 'perigo', 'safety': 'segurança', 'risk': 'risco',
  'calamity': 'calamidade', 'disaster': 'desastre',
  'problem': 'problema', 'question (issue)': 'questão',
  'solution': 'solução', 'result': 'resultado', 'effect': 'efeito',
  'cause': 'causa', 'reason': 'razão/motivo', 'purpose': 'propósito',
  'idea': 'ideia', 'opinion': 'opinião', 'thought': 'pensamento',
  'memory': 'memória', 'imagination': 'imaginação',
  'theory': 'teoria', 'method': 'método', 'system': 'sistema',
  'plan (idea)': 'plano', 'scheme': 'esquema', 'strategy': 'estratégia',
  'progress': 'progresso', 'development': 'desenvolvimento',
  'change (transformation)': 'mudança', 'reform': 'reforma',
  'improvement': 'melhoria', 'correction': 'correção',
  'connection': 'conexão', 'relation': 'relação', 'comparison': 'comparação',
  'contrast': 'contraste', 'difference': 'diferença',
  'society': 'sociedade', 'community': 'comunidade',
  'politics': 'política', 'government': 'governo', 'economy': 'economia',
  'industry': 'indústria', 'agriculture': 'agricultura', 'trade (commerce)': 'comércio',
  'nature': 'natureza', 'environment': 'meio ambiente',
  'history': 'história', 'geography': 'geografia',
  'beginning (start)': 'início', 'origin (start)': 'origem',
  'basis': 'base', 'fundamentals': 'fundamentos',
  'standard': 'padrão', 'model': 'modelo', 'example': 'exemplo',
  'style': 'estilo', 'type': 'tipo', 'kind': 'tipo/tipo',
  'quality': 'qualidade', 'grade': 'grau/nota', 'level': 'nível',
  'rank': 'posição/cargo', 'class (social)': 'classe',
  'order': 'ordem', 'rule (regulation)': 'regra',
  'situation': 'situação', 'condition': 'condição', 'state': 'estado',
  'position': 'posição', 'status': 'status/posição',
  'value': 'valor', 'price (value)': 'valor',
  'measure': 'medida', 'degree': 'grau', 'rate': 'taxa',
  'ratio': 'razão/proporção', 'proportion': 'proporção',
  'span': 'extensão', 'length': 'comprimento', 'size': 'tamanho',
  'shape': 'forma', 'figure': 'figura', 'form': 'forma',
  'outline': 'contorno', 'pattern': 'padrão',
  'scenery': 'cenário/paisagem', 'view': 'vista', 'scene': 'cena',
  'light (illumination)': 'luz',
  'shadow': 'sombra', 'shade': 'sombra',
  'color (dye)': 'cor',
  'news': 'notícia', 'information': 'informação',
  'signal': 'sinal', 'message': 'mensagem',
  'event': 'evento', 'occasion': 'ocasião', 'accident': 'acidente',
  'achievement': 'conquista', 'feat': 'façanha', 'exploit': 'feito',
  'experience': 'experiência', 'record': 'registro',
  'proof': 'prova', 'evidence': 'evidência', 'verification': 'verificação',
  'examination': 'exame', 'test': 'teste', 'exam': 'exame',
  'research': 'pesquisa', 'investigation': 'investigação',
  'discovery': 'descoberta', 'invention': 'invenção',
  'publication': 'publicação', 'printing': 'impressão',
  'broadcasting': 'transmissão', 'news (media)': 'notícia',
  'absence': 'ausência', 'presence': 'presença',
  'agreement': 'acordo', 'alliance': 'aliança', 'treaty': 'tratado',
  'contract': 'contrato', 'transaction': 'transação',
  'contribution': 'contribuição', 'compensation': 'compensação',
  'salary (pay)': 'salário', 'stipend': 'estipêndio',
  'surplus': 'excedente', 'remainder': 'resto',
  'debt': 'dívida', 'savings': 'poupança',
  'revenue': 'receita', 'expense': 'despesa', 'budget': 'orçamento',
  'tax (levy)': 'imposto', 'tariff': 'tarifa',
  'property': 'propriedade', 'goods': 'mercadorias', 'assets': 'bens',
  'treasure': 'tesouro', 'precious stone': 'pedra preciosa',
  'jewel': 'joia', 'gem': 'gema', 'pearl': 'pérola',
  'gift': 'presente', 'offering': 'oferta',
  'labor': 'trabalho', 'effort': 'esforço', 'diligence': 'diligência',

  // ── Qualidades / Adjetivos ─────────────────────────────────────────────────
  'good': 'bom/boa', 'bad': 'mau/má', 'correct': 'correto/a', 'wrong': 'errado/a',
  'true': 'verdadeiro/a', 'false': 'falso/a', 'real': 'real',
  'genuine': 'genuíno/a', 'fake': 'falso/a', 'imitation': 'imitação',
  'fast': 'rápido/a', 'quick': 'veloz', 'slow': 'lento/a', 'sudden': 'súbito',
  'hot': 'quente', 'cold': 'frio/a', 'warm': 'morno/a', 'cool': 'fresco/a',
  'dry': 'seco/a', 'wet': 'molhado/a', 'damp': 'úmido/a',
  'hard': 'duro/a', 'soft': 'macio/a', 'tough': 'resistente', 'fragile': 'frágil',
  'sharp': 'afiado/a', 'dull': 'opaco/embotado',
  'sweet': 'doce', 'bitter': 'amargo/a', 'spicy': 'picante', 'sour': 'azedo/a',
  'salty': 'salgado/a',
  'beautiful': 'bonito/a', 'pretty': 'bonito/a', 'ugly': 'feio/a',
  'elegant': 'elegante', 'graceful': 'gracioso/a', 'gentle': 'gentil',
  'lovely': 'adorável', 'splendid': 'esplêndido', 'magnificent': 'magnífico',
  'clean': 'limpo/a', 'dirty': 'sujo/a', 'pure (clean)': 'puro/a',
  'safe': 'seguro/a', 'dangerous': 'perigoso/a',
  'easy': 'fácil', 'difficult': 'difícil', 'complex': 'complexo/a',
  'simple': 'simples', 'clear': 'claro/a', 'vague': 'vago/a',
  'famous': 'famoso/a', 'unknown': 'desconhecido/a',
  'important': 'importante', 'necessary': 'necessário/a', 'useful': 'útil',
  'strange': 'estranho/a', 'normal': 'normal', 'special': 'especial',
  'ordinary': 'comum', 'rare': 'raro/a', 'unusual': 'incomum',
  'strong': 'forte', 'weak': 'fraco/a', 'robust': 'robusto/a',
  'sturdy': 'robusto/a', 'fragile (weak)': 'frágil',
  'brave': 'corajoso/a', 'cowardly': 'covarde', 'daring': 'audacioso/a',
  'fierce': 'feroz', 'violent': 'violento/a', 'cruel': 'cruel',
  'gentle (mild)': 'gentil/suave', 'calm': 'calmo/a', 'peaceful': 'pacífico/a',
  'quiet': 'quieto/calmo', 'noisy': 'barulhento/a', 'loud': 'alto/barulhento',
  'bright (cheerful)': 'alegre', 'cheerful': 'alegre', 'gloomy': 'sombrio',
  'happy': 'feliz', 'sad': 'triste', 'lonely': 'solitário/a',
  'busy': 'ocupado/a', 'free': 'livre', 'convenient': 'conveniente',
  'rich (wealthy)': 'rico/a', 'poor (needy)': 'pobre',
  'expensive': 'caro/a', 'cheap': 'barato/a',
  'new': 'novo/a', 'old (aged)': 'velho/a',
  'young (youth)': 'jovem', 'mature': 'maduro/a',
  'intelligent': 'inteligente', 'clever': 'esperto/a', 'wise': 'sábio/a',
  'foolish': 'tolo/a', 'stupid': 'estúpido/a',
  'diligent': 'diligente', 'lazy': 'preguiçoso/a',
  'honest': 'honesto/a', 'sincere': 'sincero/a',
  'proud': 'orgulhoso/a', 'humble': 'humilde',
  'kind': 'bondoso/a', 'cruel (mean)': 'cruel',
  'loyal': 'leal', 'faithful': 'fiel',
  'just': 'justo/a', 'righteous': 'reto/a',
  'selfish': 'egoísta', 'generous': 'generoso/a',
  'nervous': 'nervoso/a', 'confident': 'confiante',
  'satisfied': 'satisfeito/a', 'contented': 'satisfeito/a',
  'relax': 'relaxar', 'rested': 'descansado/a',
  'refreshing': 'refrescante', 'pleasant': 'agradável',
  'tedious': 'tedioso', 'boring': 'entediante',
  'careful': 'cuidadoso', 'careless': 'descuidado',
  'accurate': 'preciso/a', 'exact': 'exato/a',
  'suitable': 'adequado/a', 'proper': 'correto/a', 'appropriate': 'apropriado/a',

  // ── Palavras-chave N5/N4 (complemento) ─────────────────────────────────────
  'what': 'o quê', 'mean': 'médio/significar',
  'meet': 'encontrar/conhecer', 'meeting': 'reunião',
  'party': 'festa/grupo', 'association': 'associação', 'interview': 'entrevista',
  'insert': 'inserir', 'circle': 'círculo', 'yen': 'iene', 'round': 'redondo/a',
  'protrude': 'sobressair', 'part': 'parte', 'segment': 'segmento',
  'share': 'parte/porção', 'chances': 'possibilidades',
  'in front': 'na frente', 'odd number': 'número ímpar',
  'noted': 'notável', 'distinguished': 'distinto/a', 'reputation': 'reputação',
  'frequent': 'frequente', 'heavens': 'céu/paraíso', 'imperial': 'imperial',
  'become': 'tornar-se', 'air': 'ar', 'atmosphere': 'atmosfera', 'mood': 'humor',
  'insight': 'perspicácia', 'care': 'cuidado', 'favor': 'favor',
  'company': 'empresa', 'firm': 'firma',
  'void': 'nulo/vazio', 'vacant': 'vago', 'vacuum': 'vácuo',
  'set up': 'estabelecer', 'erect': 'erguer', 'going': 'indo/partida',
  'conduct': 'conduta', 'act': 'agir/ato', 'line': 'linha/fila', 'row': 'fileira',
  'hopes': 'esperanças', 'be sufficient': 'ser suficiente',
  'teachings': 'ensinamentos', 'smoke': 'fumaça', 'day off': 'folga',
  'brevity': 'brevidade', 'precedence': 'precedência',

  // ── Países (KANJIDIC2) ─────────────────────────────────────────────────────
  'spain': 'Espanha', 'turkey': 'Turquia',
  'china': 'China', 'korea': 'Coreia', 'england': 'Inglaterra',
  'america': 'América', 'france': 'França', 'germany': 'Alemanha',
  'italy': 'Itália', 'africa': 'África', 'asia': 'Ásia', 'europe': 'Europa',

  // ── Zodíaco japonês ────────────────────────────────────────────────────────
  'sign of the rat': 'signo do Rato', 'sign of the ox': 'signo do Boi',
  'sign of the tiger': 'signo do Tigre', 'sign of the rabbit': 'signo do Coelho',
  'sign of the dragon': 'signo do Dragão', 'sign of the snake': 'signo da Cobra',
  'sign of the horse': 'signo do Cavalo', 'sign of the sheep': 'signo da Ovelha',
  'sign of the monkey': 'signo do Macaco', 'sign of the rooster': 'signo do Galo',
  'sign of the dog': 'signo do Cachorro', 'sign of the boar': 'signo do Javali',

  // ── N1 – palavras mais comuns como distratores ─────────────────────────────
  'commandment': 'mandamento', 'kidnap': 'sequestrar', 'victory song': 'canto de vitória',
  'censure': 'censurar', 'rue': 'lamentar', 'horizon': 'horizonte',
  'fragrant': 'fragrante/perfumado', 'hedge': 'cerca viva', 'menacing': 'ameaçador',
  'nucleus': 'núcleo', 'husk': 'casca/palha', 'seize': 'agarrar/confiscar',
  'enclosure': 'cercado/recinto', 'isolate': 'isolar', 'point': 'ponto',
  'lagoon': 'lagoa', 'hoarse': 'rouco/a', 'fasten': 'fixar/prender',
  'thirst': 'sede', 'slippery': 'escorregadio/a', 'moreover': 'além disso',
  'birch': 'vidoeiro', 'stocks': 'ações/estoques', 'reap': 'colher/ceifar',
  'crown': 'coroa', 'intuition': 'intuição', 'persuade': 'persuadir',
  'yell': 'gritar', 'tolerant': 'tolerante', 'tree trunk': 'tronco de árvore',
  'afflicted': 'aflito/a', 'remorse': 'remorso', 'coffin': 'caixão',
  'goodwill': 'boa vontade', 'delight': 'prazer/delícia', 'oversee': 'supervisionar',
  'slacken': 'afrouxar', 'warship': 'navio de guerra', 'smiling': 'sorrindo',
  'specimen': 'espécime', 'leisure': 'lazer', 'collapse': 'colapso/desabar',
  'stubborn': 'teimoso/a', 'undertake': 'empreender', 'deed': 'feito/ação',
  'glad': 'contente/alegre', 'how many': 'quantos', 'mourning': 'luto',
  'brandish': 'brandir', 'previously': 'anteriormente', 'chess piece': 'peça de xadrez',
  'vapor': 'vapor', 'chronicle': 'crônica', 'precious': 'precioso/a',
  'hungry': 'com fome', 'ghost': 'fantasma', 'tortoise': 'tartaruga',
  'falsehood': 'falsidade', 'frolic': 'brincar', 'mimic': 'imitar',
  'deceit': 'engano', 'sacrifice': 'sacrifício', 'righteousness': 'retidão',
  'friendship': 'amizade', 'chrysanthemum': 'crisântemo', 'mandarin orange': 'tangerina',
  'instead': 'em vez disso', 'tyrannize': 'tiranizar', 'hill': 'colina',
  'shinto shrine': 'santuário xintoísta', 'decay': 'deterioração/decomposição',
  'repel': 'repelir', 'foothold': 'ponto de apoio', 'gorge': 'garganta/desfiladeiro',
  'lunatic': 'lunático/a', 'rectify': 'retificar', 'threaten': 'ameaçar',
  'entertain': 'entreter', 'echo': 'eco', 'wonder': 'maravilha/admirar',
  'congeal': 'coagular', 'brocade': 'brocado', 'tense': 'tenso/a',
  'germ': 'germe', 'collar': 'colarinho/gola', 'discreet': 'discreto/a',
  'ruler': 'régua/governante', 'drive': 'dirigir/impulso', 'yield': 'ceder/produzir',
  'winding': 'sinuoso/a', 'mulberry': 'amoreira', 'meritorious deed': 'ato meritório',
  'disclose': 'revelar', 'diameter': 'diâmetro', 'jubilation': 'júbilo',
  'recess': 'recesso', 'portable': 'portátil', 'mountain stream': 'riacho de montanha',
  'lineage': 'linhagem', 'inherit': 'herdar', 'stalk': 'caule/perseguir',
  'chicken': 'frango/galinha', 'beat': 'bater', 'greatness': 'grandiosidade',
  'undefiled': 'imaculado/a', 'hole': 'buraco', 'frugal': 'frugal',
  'concurrently': 'simultaneamente', 'sphere': 'esfera', 'strict': 'estrito/a',
  'dislike': 'não gostar', 'fist': 'punho', 'dispatch': 'despachar',
  'appear': 'aparecer', 'stern': 'severo/a', 'phantasm': 'fantasma/ilusão',
  'mysterious': 'misterioso/a', 'self': 'si mesmo', 'boast': 'vangloriar-se',
  'source': 'fonte/origem', 'string': 'corda/fio', 'arc': 'arco',
  'commandment': 'mandamento', 'fragrant': 'fragrante',
  'regulation': 'regulamentação', 'investigate': 'investigar',
  'punishment': 'punição', 'capture': 'captura', 'expedition': 'expedição',
  'clan': 'clã', 'secret': 'segredo', 'enemy': 'inimigo',
  'removal': 'remoção', 'aid': 'auxílio/ajuda', 'collapse': 'colapso',
  'butterfly': 'borboleta', 'tide': 'maré', 'challenge': 'desafio',
  'fortune': 'fortuna/sorte', 'holy': 'sagrado/a', 'pity': 'pena/compaixão',
  'tomb': 'túmulo', 'fence': 'cerca', 'abuse': 'abuso', 'cash': 'dinheiro',
  'gravity': 'gravidade', 'rainbow': 'arco-íris', 'pregnancy': 'gravidez',
  'haiku': 'haiku', 'abolish': 'abolir', 'pigeon': 'pombo',
  'tail': 'cauda', 'delicate': 'delicado/a', 'seedling': 'muda/broto',
  'rot': 'apodrecer', 'levy': 'imposto/cobrar', 'capsize': 'virar/naufragar',
  'erupt': 'entrar em erupção', 'valve': 'válvula', 'grave': 'túmulo/grave',
  'register': 'registrar', 'summit': 'cume/cúpula', 'crumble': 'desmoronar',
  'perfume': 'perfume', 'phoenix': 'fênix', 'disturb': 'perturbar',
  'obese': 'obeso/a', 'swell': 'inchar', 'conspire': 'conspirar',
  'curtain': 'cortina', 'hemp': 'cânhamo', 'cocoon': 'casulo',
  'ridicule': 'ridicularizar', 'vein': 'veia', 'exquisite': 'exquisito/refinado',
  'destroy': 'destruir', 'silence': 'silêncio', 'dart': 'dardo',
  'translate': 'traduzir', 'leap': 'saltar', 'healing': 'cura',
  'rebuke': 'repreender', 'solely': 'somente', 'soothe': 'acalmar',
  'seclude': 'isolar/recluir', 'melancholy': 'melancolia', 'entice': 'atrair',
  'masculine': 'masculino', 'dissolve': 'dissolver', 'swing': 'balançar',
  'hug': 'abraçar', 'foster': 'fomentar/criar', 'repress': 'reprimir',
  'wing': 'asa', 'naked': 'nu/a', 'column': 'coluna', 'orchid': 'orquídea',
  'perform': 'executar/se apresentar', 'detach': 'destacar', 'prudence': 'prudência',
  'captive': 'cativo/a', 'encourage': 'encorajar', 'peak': 'pico',
  'spirits': 'espíritos', 'calendar': 'calendário', 'ardent': 'ardente',
  'split': 'dividir/rachar', 'bargain': 'barganha', 'spine': 'espinha dorsal',
  'corridor': 'corredor', 'wandering': 'errante', 'bribe': 'subornar',
  'comet': 'cometa', 'axis': 'eixo', 'welfare': 'bem-estar', 'inspection': 'inspeção',
  'waiter': 'garçom', 'magnet': 'ímã', 'lacquer': 'laca', 'rapidly': 'rapidamente',
  'pardon': 'perdão', 'apologize': 'pedir desculpas', 'wicked': 'malvado/a',
  'longevity': 'longevidade', 'timber': 'madeira', 'demand': 'demanda/exigir',
  'distress': 'angústia', 'continent': 'continente', 'excel': 'superar/se destacar',
  'masses': 'massas/multidão', 'accompany': 'acompanhar', 'soup': 'sopa',
  'solemn': 'solene', 'patrol': 'patrulha', 'strand': 'fio/praia',
  'confer': 'conferir/conceder', 'preface': 'prefácio', 'gradually': 'gradualmente',
  'wound': 'ferida', 'reparation': 'reparação', 'chant': 'cântico',
  'esteem': 'estima', 'patent': 'patente', 'extract': 'extrato/extrair',
  'prosperous': 'próspero/a', 'shining': 'brilhante', 'sparkle': 'brilhar',
  'ford': 'vadear', 'symptoms': 'sintomas', 'auspicious': 'auspicioso/a',
  'appellation': 'apelação/nome', 'cosmetics': 'cosméticos', 'resemblance': 'semelhança',
  'iris': 'íris', 'banana': 'banana', 'collide': 'colidir', 'sue': 'processar',
  'detailed': 'detalhado/a', 'hinder': 'impedir', 'defer': 'adiar',
  'brew': 'fermentar/preparar', 'lock': 'travar/cadeado', 'decorate': 'decorar',
  'augment': 'aumentar', 'lips': 'lábios', 'hearing': 'audição/audiência',
  'shake': 'sacudir', 'fuel': 'combustível', 'humanity': 'humanidade',
  'inquire': 'indagar', 'swift': 'veloz', 'commander': 'comandante',
  'conjecture': 'conjectura', 'drowsy': 'sonolento/a', 'decline': 'declínio/recusar',
  'drunk': 'bêbado/a', 'adore': 'adorar', 'holy': 'sagrado',
  'haven': 'refúgio', 'crash': 'acidente/colidir', 'vine': 'trepadeira',
  'dike': 'dique', 'propose': 'propor', 'tighten': 'apertar',
  'revise': 'revisar', 'relay': 'revezamento', 'residence': 'residência',
  'remove': 'remover', 'transfer': 'transferir', 'code': 'código',
  'lament': 'lamentar', 'chastise': 'castigar', 'step': 'passo/etapa',
  'pottery': 'cerâmica', 'trunk': 'tronco/mala', 'fervent': 'fervoroso/a',
  'convex': 'convexo', 'pork': 'carne de porco', 'nun': 'freira',
  'likeness': 'semelhança', 'urine': 'urina', 'rather': 'em vez disso/prefiro',
  'sticky': 'pegajoso/a', 'settlement': 'assentamento/acordo',
  'grasp': 'agarrar/compreender', 'hegemony': 'hegemonia', 'faction': 'facção',
  'abolish': 'abolir', 'obeisance': 'reverência', 'clap': 'aplaudir',
  'urge': 'urgir/impulso', 'fell': 'derrubar', 'clique': 'grupo restrito',
  'squad': 'esquadrão', 'clan': 'clã', 'lowly': 'humilde/inferior',
  'front door': 'porta da frente', 'expose': 'expor', 'tombstone': 'lápide',
  'fertilizer': 'fertilizante', 'evade': 'evadir', 'seedling': 'muda',
  'cleverness': 'inteligência', 'musical score': 'partitura musical',
  'scorn': 'desdém', 'prostrated': 'prostrado/a', 'tomb': 'túmulo',
  'fence': 'cerca', 'highness': 'alteza', 'partial': 'parcial',
  'everywhere': 'em toda parte', 'for the first time': 'pela primeira vez',
  'pining': 'suspirando', 'observance': 'observância', 'summit': 'cúpula',
  'perfume': 'perfume', 'phoenix': 'fênix', 'sated': 'saciado/a',
  'destitution': 'miséria', 'bystander': 'espectador', 'disturb': 'perturbar',
  'spinning': 'girar/fiar', 'obese': 'obeso/a', 'conspire': 'conspirar',
  'crude': 'cru/bruto', 'intimate': 'íntimo/a', 'ditch': 'vala',
  'basin': 'bacia', 'hemp': 'cânhamo', 'curtain': 'cortina',
  'cocoon': 'casulo', 'vein': 'veia', 'destroy': 'destruir',
  'silence': 'silêncio', 'translate': 'traduzir', 'leap': 'saltar',
  'healing': 'cura', 'seclude': 'recluir', 'melancholy': 'melancolia',
  'masculine': 'masculino', 'dissolve': 'dissolver', 'wing': 'asa',
  'naked': 'nu/a', 'orchid': 'orquídea', 'detach': 'destacar',
  'captive': 'cativo/a', 'peak': 'pico', 'calendar': 'calendário',
  'split': 'rachar', 'spine': 'espinha dorsal', 'corridor': 'corredor',
  'bribe': 'subornar', 'comet': 'cometa', 'welfare': 'bem-estar',
  'inspection': 'inspeção', 'magnet': 'ímã', 'lacquer': 'laca',
  'pardon': 'perdão', 'apologize': 'pedir desculpas', 'wicked': 'malvado/a',
  'longevity': 'longevidade', 'timber': 'madeira de construção',
  'distress': 'angústia', 'continent': 'continente', 'accompany': 'acompanhar',
  'soup': 'sopa', 'solemn': 'solene', 'patrol': 'patrulha',
  'gradually': 'gradualmente', 'wound': 'ferida', 'chant': 'cântico',
  'esteem': 'estima', 'patent': 'patente', 'extract': 'extrair',
  'prosperous': 'próspero/a', 'sparkle': 'brilhar', 'ford': 'vadear',
  'symptoms': 'sintomas', 'cosmetics': 'cosméticos', 'resemblance': 'semelhança',
  'iris': 'íris', 'banana': 'banana', 'collide': 'colidir', 'sue': 'processar',
  'detailed': 'detalhado/a', 'hinder': 'impedir', 'defer': 'adiar',
  'brew': 'fermentar', 'lock': 'cadeado/travar', 'decorate': 'decorar',
  'augment': 'aumentar', 'lips': 'lábios', 'hearing': 'audição',
  'shake': 'sacudir', 'fuel': 'combustível', 'humanity': 'humanidade',
  'inquire': 'indagar', 'swift': 'veloz', 'commander': 'comandante',
  'drowsy': 'sonolento/a', 'decline': 'declinar', 'drunk': 'bêbado/a',
  'haven': 'refúgio', 'crash': 'acidente', 'vine': 'trepadeira',
  'dike': 'dique', 'propose': 'propor', 'tighten': 'apertar',
  'revise': 'revisar', 'relay': 'revezamento', 'remove': 'remover',
  'transfer': 'transferir', 'code': 'código', 'lament': 'lamentar',
  'chastise': 'castigar', 'pottery': 'cerâmica', 'fervent': 'fervoroso/a',
  'convex': 'convexo', 'pork': 'carne de porco', 'nun': 'freira',
  'urine': 'urina', 'rather': 'prefiro/em vez', 'sticky': 'pegajoso/a',
  'settlement': 'acordo/assentamento', 'grasp': 'compreender',
  'hegemony': 'hegemonia', 'faction': 'facção', 'obeisance': 'reverência',
  'urge': 'urgir', 'fell': 'derrubar', 'squad': 'esquadrão',
  'lowly': 'humilde', 'front door': 'porta da frente', 'expose': 'expor',
  'tombstone': 'lápide', 'fertilizer': 'fertilizante', 'evade': 'evadir',
  'cleverness': 'sagacidade', 'musical score': 'partitura',
  'scorn': 'desdém', 'prostrated': 'prostrado/a', 'highness': 'alteza',
  'partial': 'parcial', 'everywhere': 'por toda parte',
  'pining': 'saudade/suspiro', 'observance': 'observância',
  'destitution': 'miséria', 'bystander': 'espectador',
  'spinning': 'fiar/girar', 'crude': 'bruto/cru', 'intimate': 'íntimo/a',
  'ditch': 'vala/fosso', 'basin': 'bacia', 'straight grain': 'grão reto',
  'fascination': 'fascinação', 'secrecy': 'sigilo',
  'exquisite': 'requintado/a', 'bridegroom': 'noivo',
  'overgrown': 'superpovoado/denso', 'delusion': 'ilusão/delírio',
  'blind': 'cego/a', 'netting': 'rede', 'silence': 'silêncio',
  'family crest': 'brasão familiar', 'melting': 'derretimento',
  'dart': 'dardo', 'unlucky': 'azarado/a', 'rebuke': 'repreender',
  'solely': 'somente', 'soothe': 'acalmar', 'entice': 'seduzir',
  'foster': 'cultivar/criar', 'repress': 'reprimir',
  'column': 'coluna', 'perform': 'executar', 'prudence': 'prudência',
  'encourage': 'encorajar', 'spirits': 'espíritos', 'ardent': 'ardente',
  'bargain': 'barganha', 'wandering': 'errante', 'bribe': 'suborno',
  'axis': 'eixo', 'inspection': 'inspeção', 'conjecture': 'conjectura',
  'adore': 'adorar', 'haven': 'porto seguro',
  'propose': 'propor', 'residence': 'residência',
  'lament': 'lamentar', 'step': 'passo', 'trunk': 'tronco',
  'likeness': 'semelhança', 'grasp': 'agarrar', 'abolish': 'abolir',
  'urge': 'impulso', 'fell': 'derrubar',

  // ── N1 – palavras raras/específicas restantes ──────────────────────────────
  'charging ahead of others': 'avançar à frente', 'above-stated': 'acima mencionado',
  'miscanthus reed': 'capim-miscanto', 'tin can': 'lata', 'rut': 'sulco/rotina',
  'equestrian': 'equestre', 'skids': 'patins/deslizadores', 'hard up': 'sem dinheiro',
  'face-up': 'de frente', 'paulownia': 'paulônia (árvore)', 'parsley': 'salsinha',
  'versify': 'poetar/versificar', 'beautiful black jewel': 'joia preta preciosa',
  'pony': 'pônei', 'a coarse camlet': 'tecido áspero', 'square jewel': 'joia quadrada',
  'japanese judas-tree': 'árvore de judas japonesa', 'lightning-bug': 'vaga-lume',
  'sabre': 'sabre', 'state of suspension': 'estado de suspensão',
  'self-effacing': 'modesto/humilde', 'bowstring': 'corda de arco',
  'recreation': 'recreação', 'enlightenment': 'iluminação',
  'chinese parasol tree': 'parasol chinês', 'ancestral offering receptacle': 'altar ancestral',
  'safeguard': 'salvaguardar', 'marquis': 'marquês', 'pit': 'poço/fosso',
  'cavity': 'cavidade', 'adroit': 'hábil', 'vast': 'vasto/a',
  'constancy': 'constância', 'disconcerted': 'desconcertado/a',
  'confront': 'confrontar', 'aggression': 'agressão', 'creek': 'riacho',
  'deluge': 'dilúvio', 'wide expanse': 'grande extensão', 'gutter': 'sarjeta',
  'draft': 'rascunho/esboço', 'strangle': 'estrangular', 'hawser': 'cabo/amarra',
  'equilibrium': 'equilíbrio', 'tribute': 'tributo', 'subscription': 'assinatura',
  'fermentation': 'fermentação', 'steel': 'aço', 'torture': 'tortura',
  'overpowering': 'avassalador', 'cereals': 'cereais', 'ground-breaking': 'inovador',
  'regret': 'arrependimento', 'sociable': 'sociável', 'descendants': 'descendentes',
  'tempt': 'tentar', 'steep': 'íngreme', 'buddhist surplice': 'manto budista',
  'bond': 'laço/vínculo', 'sponsor': 'patrocinador', 'how': 'como',
  'superintend': 'supervisionar', 'coloring': 'coloração', 'plantation': 'plantação',
  'dice': 'dados', 'smash': 'esmagar', 'purification': 'purificação',
  'tailor': 'alfaiate', 'dose': 'dose', 'be clear': 'ser claro',
  'promontory': 'promontório', 'plane': 'plano/avião', 'squeeze': 'apertar',
  'conjunction (astronomy)': 'conjunção (astronomia)', 'confused': 'confuso/a',
  'bamboo grass': 'bambu-grama', 'snapshot': 'instantâneo/foto',
  'grate': 'grade/ralar', 'wretched': 'miserável', 'scaffold': 'andaime',
  'acid': 'ácido', 'temporarily': 'temporariamente', 'delicious': 'delicioso/a',
  'limb': 'membro/galho', 'climax': 'clímax', 'feminine': 'feminino/a',
  'nourishing': 'nutritivo/a', 'you': 'você', 'emperor\'s seal': 'selo imperial',
  'sow (seeds)': 'semear', 'eventide': 'entardecer', 'tenacious': 'tenaz',
  'recollect': 'recordar', 'turf': 'gramado', 'cottage': 'cabana/chalé',
  'intercept': 'interceptar', 'ladle': 'concha/colher grande',
  'shaku': 'shaku (unidade)', 'baron': 'barão', 'bar-tending': 'bartender',
  'explanation': 'explicação', 'loneliness': 'solidão', 'particularly': 'particularmente',
  'hunt': 'caçar', 'purport': 'propósito/alegar', 'confucian': 'confuciano',
  'captured': 'capturado/a', 'concerning': 'relativo a', 'stinking': 'fedorento/a',
  'allot': 'alocar', 'astringent': 'adstringente', 'cram school': 'cursinho',
  'mellow': 'suave/maduro', 'sagacious': 'sagaz', 'wink': 'piscar o olho',
  'type of morning glory': 'tipo de ipomeia', 'a good horse': 'bom cavalo',
  'quasi-': 'quase-', 'sequential': 'sequencial', 'decameron': 'decamerão',
  'martyrdom': 'martírio', 'abide by': 'cumprir/acatar', 'pure sake': 'saquê puro',
  'measuring box': 'caixa de medição', 'exhort': 'exortar', 'wee hours': 'madrugada',
  'treetops': 'copas das árvores', 'char': 'carvão/carbonizar',
  'nitrate': 'nitrato', 'reef': 'recife', 'imperial edict': 'édito imperial',
  'lot': 'lote/sorteio', 'lass': 'moça/jovem', 'embarrass': 'envergonhar',
  'encroach': 'invadir', 'with child': 'grávida', 'hazelnut': 'avelã',
  'immersed': 'imerso/a', 'manchu dynasty': 'dinastia manchu', 'sire': 'majestade',
  'checkup': 'exame médico', 'tremendously': 'tremendamente', 'ought': 'dever',
  'chic': 'chique', 'consummate': 'consumado/a', 'be aggravated': 'piorar',
  'hinge': 'dobradiça', 'chick': 'pintinho', 'set': 'conjunto/definir',
  'lucidity': 'lucidez', 'measurement': 'medição', 'rapids': 'corredeiras',
  'furrow': 'sulco/ruga', 'just so': 'exatamente assim', 'animal sacrifice': 'sacrifício animal',
  'boom': 'crescimento/explosão', 'solicit': 'solicitar', 'departed': 'falecido',
  'adjusted': 'ajustado/a', 'vessels': 'vasos/navios', 'chop': 'picar/cortar',
  'enroll': 'matricular', 'tracks': 'trilhos/pistas', 'bungling': 'incompetente',
  'vicarious': 'vicário', 'stealth': 'furtividade', 'hermit': 'eremita',
  'proclaim': 'proclamar', 'fan': 'leque/fã', 'plug': 'plugue/tampar',
  'submerge': 'submergir', 'rotation': 'rotação', 'slender': 'esbelto/a',
  'recommend': 'recomendar', 'tread': 'pisar', 'transition': 'transição',
  'pig iron': 'ferro-gusa', 'fresh': 'fresco/a', 'steadily': 'constantemente',
  'zen': 'zen', 'darning': 'remendo', 'set aside': 'reservar/deixar de lado',
  'alienate': 'alienar', 'cornerstone': 'pedra angular', 'coarse': 'grosseiro/a',
  'elementary': 'elementar', 'accusation': 'acusação', 'thwart': 'frustrar',
  'buddhist priest': 'monge budista', 'genesis': 'gênese', 'play music': 'tocar música',
  'nest': 'ninho', 'villa': 'villa/mansão', 'interment': 'enterro',
  'seaweed': 'algas marinhas', 'encounter': 'encontrar', 'boisterous': 'agitado/barulhento',
  'stimulate': 'estimular', 'instant': 'instante', 'vulgar': 'vulgar',
  'belong': 'pertencer', 'washing': 'lavagem', 'degenerate': 'degenerar',
  'burdensome': 'oneroso/a', '-proof': 'à prova de', 'neglect': 'negligenciar',
  'attitude': 'atitude', 'stagnate': 'estagnar', 'apprehend': 'apreender',
  'regiment': 'regimento', 'blackened eyebrows': 'sobrancelhas escurecidas',
  'sea bream': 'pargo (peixe)', 'waterfall': 'cachoeira', 'eminent': 'eminente',
  'peck': 'bicar', 'consign': 'consignar', 'voiced': 'sonoro/a',
  'consent': 'consentimento', 'however': 'porém', 'undress': 'despir',
  'southeast': 'sudeste', 'rust-colored': 'cor de ferrugem', 'sigh': 'suspirar',
  'edge': 'borda/fio', 'nativity': 'natividade', 'immature': 'imaturo/a',
  'doth': 'faz (arcaico)', 'amass': 'acumular', 'pursue': 'perseguir',
  'regularity': 'regularidade', 'plug up': 'tampar', 'legitimate wife': 'esposa legítima',
  'pluck': 'arrancar/coragem', 'inmost': 'mais íntimo', 'casting': 'fundição',
  'condolences': 'condolências', 'indications': 'indicações', 'penal': 'penal',
  'dilate': 'dilatar', 'hop': 'saltar', 'imperial order': 'ordem imperial',
  'majestic plural': 'plural majestático', 'tranquilize': 'tranquilizar',
  'exhibit': 'exibir', 'chinquapin': 'castanheiro', 'hillock': 'montículo',
  'zelkova tree': 'zelkova (árvore)', 'pickling': 'picles/conserva',
  'camellia': 'camélia', 'two-mat area': 'espaço de dois tatames',
  'pongee (a knotted silk cloth)': 'seda crua', 'angling': 'pesca com anzol',
  'upright': 'ereto/honrado', 'courts': 'tribunais/quadras', 'serving our elders': 'servir os mais velhos',
  'water\'s edge': 'margem da água', 'rowboat': 'barco a remo',
  'annexed': 'anexado/a', 'spit': 'cuspir', 'big dipper': 'Ursa Maior',
  'guy': 'cara/homem', "t'ang": 'dinastia Tang', 'ridgepole': 'cumeeira',
  'pox': 'varíola', 'overall': 'geral/macacão', 'mimeograph': 'mimeógrafo',
  'leaping up': 'saltar', 'yearn after': 'anseiar por', 'mountain peak': 'cume de montanha',
  'coach': 'treinador/carruagem', 'nara': 'Nara', 'what?': 'o quê?',
  'lull': 'acalmar/calmaria', 'press': 'pressionar', 'straw rope': 'corda de palha',
  'camphor tree': 'cânfora (árvore)', 'ii': 'ii', 'from': 'de/desde',
  'of': 'de', 'comma-design': 'padrão em vírgula', 'repudiate': 'repudiar',
  'bush clover': 'lespedeza', 'dr.': 'Dr./Doutor', 'liner': 'navio/forro',
  'truss': 'treliça/suporte', 'consort': 'consorte', 'conveyor': 'transportador',
  'paddy ridge': 'borda do arrozal', 'ooze': 'vazar lentamente', 'holly': 'azevinho',
  'beautiful woman': 'mulher bela', 'spotted': 'manchado/avistado',
  'v.i.p.': 'VIP', 'repeatedly': 'repetidamente', 'affixed': 'afixado/a',
  'butterbur': 'fáfaro (planta)', 'aroused': 'excitado/a', 'stirred up': 'agitado',
  'distract': 'distrair', 'third class': 'terceira classe', 'mannerism': 'maneirismo',
  'bubbles': 'bolhas', 'placenta': 'placenta', 'show symptoms of': 'mostrar sintomas de',
  'tassel': 'borla', 'so-and-so': 'fulano/a', 'me': 'me/eu',
  'slap': 'tapa', 'flip': 'virar/girar', 'chafe': 'irritar',
  'witch': 'bruxa', 'also': 'também', 'or again': 'ou então',
  'cartoon': 'desenho animado', 'headland': 'promontório', 'type of deciduous tree': 'árvore caducifólia',
  'monme': 'monme (unidade)', 'question mark': 'ponto de interrogação',
  'permanence': 'permanência', 'citron': 'cidra', 'furthermore': 'além disso',
  'kiln': 'forno/fornalha', 'far off': 'longe', 'dairy products': 'laticínios',
  'perusal': 'leitura atenta', 'pear tree': 'pereira', 'diarrhea': 'diarreia',
  'ri': 'ri (unidade japonesa)', 'sulphur': 'enxofre', 'hump': 'corcova',
  'game-hunting': 'caça', 'provisions': 'provisões', 'fact': 'fato',
  'mausoleum': 'mausoléu', 'rin': 'rin (unidade)', 'look to': 'olhar para',
  'neighboring': 'vizinho/a', 'chinese unicorn': 'unicórnio chinês',
  'lapis lazuli': 'lápis-lazúli', 'bases': 'bases', 'sound of jewels': 'som de joias',
  'small bell': 'sininho', 'inferiority': 'inferioridade', 'tempering': 'têmpera',
  'hearth': 'lareira', 'melodious': 'melodioso/a', 'watchtower': 'torre de vigia',
  'fief': 'feudo', 'yamato': 'Yamato', 'beguile': 'enganar/seduzir',
  'urge to eat': 'apetite', 'mountains towering in a row': 'montanhas em fileira',
  'the pleiades': 'as Plêiades', 'bookmark': 'marcador de página',
  'coconut tree': 'coqueiro', 'burr': 'rebarbas/ouriço', 'sparkling water': 'água com gás',
  'alike': 'semelhante', 'deep and broad (water)': 'profundo e largo (água)',
  'gargle': 'gargarejo', 'water route': 'rota aquática', 'beautiful as a jewel': 'belo como joia',
  'pupil of the eye': 'pupila do olho', 'a reed instrument': 'instrumento de junco',
  'figured cloth': 'tecido figurado', 'dried meat': 'carne seca',
  'the violet': 'a violeta', 'strong and brave': 'forte e bravo', 'edify': 'edificar',
  'eulogy': 'elogio/panegírico',

  // ── Termos JLPT / linguística ──────────────────────────────────────────────
  'grammar': 'gramática', 'vocabulary': 'vocabulário', 'pronunciation': 'pronúncia',
  'kanji': 'kanji', 'hiragana': 'hiragana', 'katakana': 'katakana',
  'learning': 'aprendizado',

  // ── N5 – faltantes ─────────────────────────────────────────────────────────
  'interval': 'intervalo', 'electricity': 'eletricidade', 'every': 'todo/cada',

  // ── N4 – faltantes ─────────────────────────────────────────────────────────
  'world': 'mundo', 'sino-': 'sino-/chinês', 'homecoming': 'retorno a casa',
  'rouse': 'despertar', 'gone': 'partido/desaparecido', 'business': 'negócio',
  'near': 'perto', 'ward': 'bairro/distrito', 'plot': 'parcela/trama',
  'lightly': 'levemente', 'ray': 'raio', 'fond': 'afeiçoado/gostar',
  'craft': 'artesanato/habilidade', 'fit': 'adequado/encaixar',
  'products': 'produtos', 'attend': 'comparecer/atender',
  'commence': 'começar', 'private': 'privado/particular',
  'matter': 'assunto/matéria', 'oneself': 'a si mesmo', 'substance': 'substância',
  'copy': 'cópia', 'someone': 'alguém', 'dwell': 'habitar/morar',
  'springtime': 'época de primavera', 'place': 'lugar',
  'sultry': 'abafado/quente', 'location': 'localização', 'escort': 'escolta',
  'tribe': 'tribo', 'plump': 'rechonchudo/a', 'substitute': 'substituto',
  'pedestal': 'pedestal/base', 'topic': 'tópico/assunto', 'tea': 'chá',
  'don': 'vestir', 'traffic': 'tráfego', 'lower': 'baixar/inferior',
  'revolve': 'girar', 'degrees': 'graus', 'same': 'mesmo/igual',
  'public chamber': 'câmara pública', 'departure': 'partida/saída',
  'meal': 'refeição', 'ill': 'doente', 'negative': 'negativo',
  'thing': 'coisa', 'convenience': 'conveniência', 'exertion': 'esforço',
  'direction': 'direção', 'flavor': 'sabor', 'question': 'pergunta/questão',
  'possess': 'possuir', 'weekday': 'dia da semana', 'utilize': 'utilizar',
  'trip': 'viagem',

  // ── N3 – faltantes ─────────────────────────────────────────────────────────
  'reformation': 'reforma', 'contraption': 'engenhoca', 'ashes': 'cinzas',
  'storey': 'andar (de prédio)', 'shellfish': 'mariscos', 'harm': 'dano/prejuízo',
  'broaden': 'ampliar', 'assurance': 'garantia', 'leather': 'couro',
  'lively': 'animado/vivo', 'drought': 'seca', 'perfect': 'perfeito/a',
  'emotion': 'emoção', 'accustomed': 'acostumado/a', 'interchange': 'intercâmbio',
  'ring': 'anel/argola', 'watch over': 'vigiar', 'simplicity': 'simplicidade',
  'outlook': 'perspectiva', 'boulder': 'pedregulho', 'rejoice': 'alegrar-se',
  'period': 'período', 'loom': 'tear/surgir', 'seasons': 'estações',
  'scribe': 'escriba', 'doubt': 'dúvida', 'deliberation': 'deliberação',
  'packed': 'lotado/comprimido', 'guest': 'hóspede/convidado',
  'inverted': 'invertido/a', 'class': 'classe/aula', 'reside': 'residir',
  'fishing': 'pesca', 'together': 'juntos', 'co-': 'co-/junto',
  'boundary': 'fronteira/limite', 'cramped': 'apertado/a', 'extreme': 'extremo',
  'accidentally': 'acidentalmente', 'corner': 'canto/esquina',
  'mister': 'senhor', 'instruction': 'instrução', 'flock': 'rebanho/bando',
  'army': 'exército', 'person in charge': 'responsável', 'lean': 'inclinar/magro',
  'mould': 'molde', 'awe': 'reverência/temor', 'sutra': 'sutra',
  'admonish': 'admoestar', 'technique': 'técnica', 'welcome': 'boas-vindas',
  'affair': 'assunto/caso', 'healthy': 'saudável', 'authority': 'autoridade',
  'flats': 'planícies', 'precipitous': 'íngreme', 'dwindle': 'diminuir',
  'present': 'presente/atual', 'limit': 'limite', 'individual': 'indivíduo',
  'call': 'chamar', 'harden': 'endurecer', 'happenstance': 'acaso',
  'wither': 'murchar', 'employ': 'empregar', 'mutually': 'mutuamente',
  'honorable': 'honroso/a', 'mingle': 'misturar-se', 'climate': 'clima',
  'public': 'público/a', 'merit': 'mérito', 'yonder': 'além/lá',
  'ease': 'facilidade', 'grow late': 'ficar tarde', 'posture': 'postura',
  'stiff': 'rígido/a', 'till': 'cultivar/até', 'laid waste': 'devastado',
  'lecture': 'palestra/aula', 'outskirts': 'arredores', 'mineral': 'mineral',
  'incense': 'incenso', 'revelation': 'revelação', 'crowded': 'lotado/a',
  'quandary': 'dilema', 'marriage': 'casamento', 'mix': 'misturar',
  'distinction': 'distinção', 'squat': 'agachar', 'again': 'novamente',
  'utmost': 'máximo/extremo', 'pick': 'escolher/colher', 'year-end': 'fim de ano',
  'settle (debt': 'liquidar (dívida)', 'dainty': 'delicado/requintado',
  'slope': 'encosta/rampa', 'yesterday': 'ontem', 'tome': 'tomo/volume',
  'guess': 'adivinhar', 'miscellaneous': 'variado/diverso',
  'nonplussed': 'perplexo/a', 'pay respects': 'prestar homenagens',
  'thorn': 'espinho', 'director': 'diretor/a', 'expert': 'especialista',
  'intention': 'intenção', 'bough': 'galho', 'fat': 'gordo/gordura',
  'part of speech': 'classe gramatical', 'becoming': 'tornar-se/decente',
  'newborn babe': 'recém-nascido', 'buddhist temple': 'templo budista',
  'reign': 'reinado', 'discriminating': 'criterioso/a', 'reality': 'realidade',
  'discard': 'descartar', 'guard': 'guarda/proteger', 'species': 'espécie',
  'impart': 'transmitir', 'circumference': 'circunferência',
  'discipline': 'disciplina', 'tender': 'delicado/tenro', 'mention': 'mencionar',
  'semi-': 'semi-', 'dispose': 'dispor', 'thong': 'tira/correia',
  'signature': 'assinatura', 'exclude': 'excluir', 'make a deal': 'fazer acordo',
  'leader': 'líder', 'bed': 'cama/leito', 'acquiesce': 'aquiescer',
  'beckon': 'acenar', 'rise up': 'erguer-se', 'illuminate': 'iluminar',
  'government ministry': 'ministério', 'elephant': 'elefante', 'prize': 'prêmio',
  'usual': 'habitual', 'article': 'artigo', 'status quo': 'status quo',
  'tatami mat': 'tatame', 'steam': 'vapor', 'post': 'posto/cargo',
  'contact': 'contato', 'have the honor to': 'ter a honra de',
  'gods': 'deuses', 'somebody': 'alguém', 'quake': 'tremor/terremoto',
  'blow': 'soprar', 'forces': 'forças', 'sex': 'sexo', 'turn into': 'transformar-se em',
  'clear up': 'esclarecer', 'made in...': 'fabricado em...',
  'seat': 'assento/lugar', 'volume': 'volume', 'exploits': 'façanhas',
  'touch': 'tocar', 'fold': 'dobrar', 'establishment': 'estabelecimento',
  'node': 'nó', 'discontinue': 'descontinuar', 'fortune-telling': 'adivinhação',
  'specialty': 'especialidade', 'elect': 'eleger', 'virtuous': 'virtuoso/a',
  'sort of thing': 'tipo de coisa', 'pair': 'par', 'stratum': 'estrato/camada',
  'search': 'busca/pesquisa', 'maneuver': 'manobra', 'parch': 'ressecar',
  'inter-': 'inter-', 'attire': 'traje/vestimenta', 'statue': 'estátua',
  'entrails': 'entranhas', 'presents': 'presentes/dádivas', 'bundle': 'fardo/pacote',
  'fathom': 'sondar/compreender', 'graduate': 'graduado/a', 'revered': 'reverenciado/a',
  'damage': 'dano', 'other': 'outro/a', 'strike': 'golpe/greve',
  'vis-a-vis': 'frente a frente', 'sack': 'saco/demitir', 'no.': 'n.º/número',
  'laundry': 'lavanderia/roupa', 'accomplished': 'realizado/habilidoso',
  'shouldering': 'carregar nos ombros', 'grope': 'tateiar',
  'charcoal': 'carvão', 'group': 'grupo', 'severance': 'separação/rompimento',
  'warmth': 'calor/aconchego', 'placement': 'colocação', 'fabricate': 'fabricar',
  'livestock': 'gado/animais de criação', 'mid-air': 'no ar/suspensão',
  'stop-over': 'escala/parada', 'renowned': 'renomado/a', 'portent': 'presságio',
  'tune': 'melodia/afinar', 'transcend': 'transcender', 'straightaway': 'imediatamente',
  'chase': 'perseguir', 'pain': 'dor', 'halt': 'parar/parada',
  'determine': 'determinar', 'bottom': 'fundo/base', 'courtyard': 'pátio',
  'extent': 'extensão', 'mud': 'lama', "bull's eye": 'alvo/mosca',
  'unfold': 'desdobrar', 'spot': 'ponto/lugar', 'transmit': 'transmitir',
  'mr.': 'sr./senhor', 'on foot': 'a pé', 'transit': 'trânsito',
  'toil': 'trabalho árduo', 'angry': 'irritado/a', 'frozen': 'congelado/a',
  'hot water': 'água quente', 'etc.': 'etc.', 'cylinder': 'cilindro',
  'arrival': 'chegada', 'guidance': 'orientação', 'juvenile': 'jovem/juvenil',
  'single': 'único/solteiro', 'cloudy weather': 'tempo nublado', 'milk': 'leite',
  'acknowledge': 'reconhecer', 'trouble': 'problema/dificuldade',
  'concentrated': 'concentrado/a', 'brain': 'cérebro', 'waves': 'ondas',
  'rend': 'rasgar', 'failure': 'falha/fracasso', 'stature': 'estatura',
  'overnight stay': 'pernoite', 'dilute': 'diluir', 'barley': 'cevada',
  'texture': 'textura', 'hair of the head': 'cabelo', 'slip out': 'escorregar/sair',
  'judgement': 'julgamento', 'anti-': 'anti-', 'printing block': 'bloco de impressão',
  'carrier': 'portador/transportador', 'marketing': 'marketing/comércio',
  'turn': 'virar/turno', 'negate': 'negar', 'he': 'ele',
  'criticism': 'crítica', 'compare': 'comparar', 'exhausted': 'esgotado/a',
  'pelt': 'pele (animal)', 'incur': 'incorrer/sofrer', 'equip': 'equipar',
  'beauty': 'beleza', 'equal': 'igual', 'invariably': 'invariavelmente',
  'writing brush': 'pincel', 'signpost': 'sinalização', 'surface': 'superfície',
  'evaluate': 'avaliar', 'second (1/60 minute)': 'segundo (tempo)',
  'adhere': 'aderir', 'lady': 'senhora/dama', 'wealth': 'riqueza',
  'linen': 'linho', 'dreadful': 'terrível', 'universal': 'universal',
  'floating': 'flutuante', 'token': 'símbolo/ficha', 'dance': 'dança',
  'section': 'seção', 'vice-': 'vice-', 'restore': 'restaurar',
  'hanging scroll': 'rolo suspenso', 'seethe': 'ferver/agitar', 'buddha': 'Buda',
  'flour': 'farinha', 'even': 'até mesmo/uniforme', 'closed': 'fechado/a',
  'one-sided': 'unilateral', 'compilation': 'compilação', 'environs': 'arredores',
  'supplement': 'suplemento', 'recruit': 'recrutar', 'embrace': 'abraçar',
  'call on': 'visitar/apelar', 'deceased': 'falecido/a', 'outburst': 'explosão',
  'ward off': 'afastar/repelir', 'bury': 'enterrar', 'sheet of...': 'folha de...',
  'task': 'tarefa', 'nothingness': 'nada/vazio', 'astray': 'perdido/desviado',
  'chirp': 'chilrear', 'cotton': 'algodão', 'fur': 'pele/pelo',
  're-': 're-', 'transport': 'transporte', 'tenderness': 'ternura',
  'courage': 'coragem', 'wherefore': 'portanto', 'mail': 'correio/e-mail',
  'beforehand': 'antecipadamente', 'too much': 'demais/excessivo',
  'bestow': 'conceder/outorgar', 'deposit': 'depósito', 'infancy': 'infância',
  'esq.': 'Esq./advogado', 'sunshine': 'luz do sol', 'bathe': 'banhar-se',
  'the following': 'o seguinte', 'entwine': 'entrelaçar', 'riot': 'tumulto',
  'abbreviation': 'abreviação', 'current': 'corrente/atual', 'detain': 'deter',
  'grains': 'grãos', 'complete': 'completo/concluir', 'heal': 'curar',
  'quantity': 'quantidade', 'jurisdiction': 'jurisdição', 'wheel': 'roda',
  'sort': 'classificar/tipo', 'orders': 'ordens/pedidos', 'salute': 'saudar',
  'age': 'idade/era', 'curriculum': 'currículo', 'file': 'arquivo/ficha',
  'romance': 'romance', 'take along': 'levar consigo',   'argument': 'argumento',
  'harmony': 'harmonia',
  "bull's eye": 'alvo certeiro',

  // ── Complemento: palavras ainda em inglês detectadas no banco ──────────────
  'lotus': 'lótus', 'design': 'design/padrão', 'camp': 'acampamento',
  'distant': 'distante', 'congratulations': 'parabéns', 'feelings': 'sentimentos',
  'angle': 'ângulo/canto', 'grant': 'conceder', 'contain': 'conter',
  'emulate': 'emular/rivalizar', 'pinch': 'beliscar', 'barbarian': 'bárbaro/a',
  'i': 'eu', 'exist': 'existir', 'gauze': 'gaze', 'excuse': 'desculpa',
  'star': 'estrela', 'refined': 'refinado/a', 'chief': 'chefe',
  'un-': 'não-/sem-', 'commonplace': 'comum/banal', 'jasmine': 'jasmim',
  'pathetic': 'patético/a', 'hollyhock': 'malva-rosa', 'madder': 'ruiva (planta)',
  'grip': 'agarrar/pegar', 'catalpa tree': 'catálpa (árvore)', 'pressure': 'pressão',
  'handle': 'lidar com/alça', 'brilliant fabric design': 'estampa brilhante',
  'freshwater trout': 'truta de água doce', 'darkness': 'escuridão',
  'reliant': 'dependente/confiante', 'admirable': 'admirável',
  'surround': 'cercar/rodear', 'committee': 'comitê', 'intimidate': 'intimidar',
  'consolation': 'consolo', 'do': 'fazer', 'uncommon': 'incomum',
  'shift': 'turno/mudar', 'fiber': 'fibra', 'bequeath': 'legar/transmitir',
  'well': 'bem/poço', 'range': 'alcance/gama', 'bring up': 'criar/educar',
  'cultural progress': 'progresso cultural', 'deviate': 'desviar',
  'rice plant': 'planta de arroz', 'potato': 'batata', 'license': 'licença',
  'stamp': 'carimbo/selo', 'employee': 'funcionário/a', 'matrimony': 'matrimônio',
  'descendent': 'descendente', 'inst.': 'mês corrente', 'shade': 'sombra/tonalidade',
  'eaves': 'beiral', 'feathers': 'penas', 'whirlpool': 'redemoinho',
  'shadow': 'sombra', 'reflect': 'refletir', 'flourish': 'florescer/prosperar',
  'sparkle of jewelry': 'brilho de joias', 'defense': 'defesa',
  'recitation': 'recitação', 'pointed': 'pontudo/a', 'fluid': 'fluido',
  'epidemic': 'epidemia', 'benefit': 'benefício', 'ecstasy': 'êxtase',
  'audience': 'audiência/público', 'surpass': 'superar', 'review': 'revisão',
  'banquet': 'banquete', 'prolong': 'prolongar', 'abet': 'incitar',
  'performance': 'apresentação', 'inflammation': 'inflamação', 'at': 'em/no',
  'concave': 'côncavo', 'apply': 'aplicar', 'flourishing': 'florescente',
  'sideways': 'de lado', 'assault': 'assalto', 'venerable old man': 'ancião respeitado',
  'roof': 'telhado', 'recollection': 'recordação', 'the latter': 'o segundo/este último',
  'wholesale': 'atacado (comércio)', 'sham': 'fingimento/impostura',
  'nursing': 'enfermagem/amamentação', 'excellent': 'excelente', 'can': 'poder/lata',
  'applaud': 'aplaudir', 'marry into': 'casar-se (entrar na família)',
  'department': 'departamento', 'spare time': 'tempo livre', 'eggplant': 'berinjela',
  'baggage': 'bagagem', 'splendor': 'esplendor', 'candy': 'doce/bala',
  'chapter': 'capítulo', 'freight': 'frete/carga', 'overdo': 'exagerar',
  'be hazy': 'ser nebuloso', 'mosquito': 'mosquito', 'ego': 'ego',
  'brush-stroke': 'pincelada', 'gracious': 'gracioso/a', 'starve': 'passar fome',
  'jammed in': 'encravado/preso', 'unravel': 'desvendar/desfiar',
  '-times': 'vezes', 'clod': 'torrão/pessoa grossa', 'demolition': 'demolição',
  'suspicious': 'suspeito/a', 'repent': 'arrepender-se',
  'consult with': 'consultar', 'wise': 'sábio/a',
};

// ─── Mapeamento de frases compostas ───────────────────────────────────────────
const PHRASE_MAP = {
  'go out': 'sair', 'come out': 'surgir/sair', 'put out': 'emitir',
  'stand up': 'ficar em pé', 'set up': 'estabelecer',
  'look at': 'olhar para', 'be sufficient': 'ser suficiente',
  'grow dark': 'escurecer', 'wake up': 'acordar',
  'get up': 'levantar-se', 'give birth': 'dar à luz',
  'make effort': 'fazer esforço', 'carry out': 'realizar',
  'branch off': 'ramificar-se', 'flow into': 'fluir para',
  "one's lot": 'destino/sorte', 'minute of time': 'minuto',
  'in front': 'na frente', 'odd number': 'número ímpar',
  'ten thousand': 'dez mil', 'road-way': 'caminho/estrada',
  'be blinded': 'ser ofuscado', 'bear up': 'aguentar',
  'big around': 'grande em volta', 'big brother': 'irmão mais velho',
  'first time': 'pela primeira vez', 'go-between': 'intermediário',
  'take pleasure in': 'ter prazer em', 'run alongside': 'correr ao lado',
  'open sea': 'mar aberto', 'long-distance': 'longa distância',
  'good crops': 'boa colheita', 'good luck': 'boa sorte',
  'male mythical bird': 'ave mitológica masculina',
  'national flag': 'bandeira nacional', 'rising sun': 'sol nascente',
  'home country': 'terra natal', 'home town': 'cidade natal',
  'best regards': 'cumprimentos',
  'to be': 'ser/estar', 'each other': 'um ao outro',
  'all the more': 'ainda mais',
  'once upon a time': 'era uma vez',
  'by means of': 'por meio de',
  'give up': 'desistir', 'take over': 'assumir',
  'pass through': 'passar por', 'pass away': 'falecer',
  'come back': 'voltar', 'go back': 'voltar',
  'break down': 'quebrar', 'break up': 'separar',
  'grow up': 'crescer', 'grow old': 'envelhecer',
  'pick up': 'pegar', 'put up': 'erguer',
  'cut off': 'cortar', 'set free': 'libertar',
  'send forth fragrance': 'exalar perfume',
  'place on the head': 'colocar na cabeça',
  'become dark': 'escurecer',
  'spring water': 'água de nascente',
  'boiled rice': 'arroz cozido',
  'palm of hand': 'palma da mão',
  '11pm-1am': '23h–1h', '11am-1pm': '11h–13h',
  'first sign of chinese zodiac': '1º signo do zodíaco',
  'seventh sign of chinese zodiac': '7º signo do zodíaco',
  'bring up': 'criar/educar', 'consult with': 'consultar',
  'be hazy': 'ser nebuloso', 'marry into': 'casar-se',
  'sparkle of jewelry': 'brilho de joias',
  'venerable old man': 'ancião respeitado',
  'brilliant fabric design': 'estampa brilhante',
  'freshwater trout': 'truta de água doce',
  'cultural progress': 'progresso cultural',
};

/**
 * Traduz um único segmento de significado (sem `;`).
 */
const translateSegment = (segment) => {
  const trimmed = segment.trim();
  if (!trimmed) return '';
  const lower = trimmed.toLowerCase();

  // Lookup direto
  if (MEANING_MAP[lower]) return MEANING_MAP[lower];

  // Frases compostas
  if (PHRASE_MAP[lower]) return PHRASE_MAP[lower];

  // Remove parênteses e tenta novamente: "big (size)" → "big"
  const noParens = lower.replace(/\s*\(.*?\)\s*/g, '').trim();
  if (noParens && MEANING_MAP[noParens]) return MEANING_MAP[noParens];
  if (noParens && PHRASE_MAP[noParens]) return PHRASE_MAP[noParens];

  // Padrão "counter for X" → "contador de X"
  if (lower.startsWith('counter for ')) {
    return `contador de ${trimmed.slice('counter for '.length)}`;
  }

  // Fallback: mantém original
  return trimmed;
};

/**
 * Traduz a string completa de significados (pode ter vários separados por '; ').
 * Ex.: "fire; flame" → "fogo; chama"
 */
export const translateMeaning = (englishMeaning) => {
  if (!englishMeaning) return '';
  const normalized = englishMeaning.replace(/, /g, '; ');
  return normalized
    .split('; ')
    .map(translateSegment)
    .filter(Boolean)
    .join('; ');
};

/**
 * Traduz APENAS o primeiro significado — para exibição nas opções de batalha.
 * Ex.: "abundant; rico/a; fertile" → "abundante"
 *      "fire; flame; blaze"        → "fogo"
 */
export const translateFirstMeaning = (englishMeaning) => {
  if (!englishMeaning) return '';
  const normalized = englishMeaning.replace(/, /g, '; ');
  const first = normalized.split('; ')[0];
  return translateSegment(first) || first;
};
